version: '2'
services:
    nginx:
        image: nginx:alpine
        container_name: ${APP_NAME}-nginx
        restart: always
        ports:
            - 3000:80
        volumes:
            - ./:/var/www
            - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
    phpMyAdmin:
        image: phpmyadmin/phpmyadmin
        container_name: ${APP_NAME}-phpmyadmin
        restart: always
        ports:
            - 3001:80
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_DATABASE}
        links:
            - mysql:db
        depends_on:
            - mysql
    php:
        build: ./docker/php
        container_name: ${APP_NAME}-php
        restart: always
        volumes:
            - ./:/var/www
        depends_on:
            - mysql
        environment:
            DB_HOST: mysql
            DB_PORT: 3306
            DB_DATABASE: ${DB_DATABASE}
            DB_USERNAME: root
            DB_PASSWORD: ${DB_PASSWORD}
    mysql:
        image: mysql:5.6
        container_name: ${APP_NAME}-mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD:  ${DB_PASSWORD}
            MYSQL_DATABASE:  ${DB_DATABASE}